switching to own model called units insteand of submodules
Signed-off-by: Denis Zalevskiy <denis.zalevskiy@jolla.com>

diff --git a/src/git-vault-unit-commit b/src/git-vault-unit-commit
--- a/src/git-vault-unit-commit
+++ b/src/git-vault-unit-commit
@@ -2,7 +2,7 @@
 
 src=`dirname $0`
 src=`cd $src;pwd`
-source $src/the-vault_misc $src
+source $src/vault-misc $src
 
 ensure_param_count_exit_usage $# 2 "<unit_name> <commit_message>"
 
@@ -22,8 +22,15 @@ if [ "$branch" != "master" ]; then
     error 22 "Submodule commit should be run only when on master, got $branch"
 fi
 
-git status --porcelain -z | xargs -0 the-vault-submodule-status-process
-git commit -a -m "vault-commit" \
-    && git notes add -m "vault-commit-$msg" HEAD
+processed=$(git status --porcelain -z | xargs -0 git vault-unit-status-process)
+rc=$?
+if [ $rc -ne 0 ]; then
+    error $rc "Error processing status for $name"
+elif [ "x$processed" != "x" ]; then
+    git commit -m "$msg"
+    echo $processed
+else
+    trace "Nothing to commit for $name"
+fi
 
 
